baseURL = "https://nullerh.github.io/02467_group4/"
title = "Group 4 - 02467 Exam Project"
description = "Amazon fine foods reviews"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Peter GGGGGGGGGGGGGGGG", "Inga Jensen", "Mikkel Andersen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/nullerh/02467_group4/"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

