baseURL = "https://eortvald.github.io/02467_group4/"
title = "Amazon Fine Foods Project"
description = "Analysis of Amazon fine foods reviews"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Emil Ortvald - s194276", "Joachim Christensen - s173743", "Peter Hulgaard - s194277"]
    notebook = "/Food_project_main.html"
    data = "https://drive.google.com/drive/folders/1LdzDLUJ0fnkbmTHLJu8Zv6AfVEaCX0d4"
    github = "https://github.com/Joachimchristensen/02467-comsocsci-examproject"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Summary"
        link = "/summary"
    

