baseURL = "https://nullerh.github.io/02467_group4/"
title = "Amazon fine food reviews"
description = "Analysis of Amazon fine foods reviews"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Emil Ortvald - s194276", "Joachim Christensen - s173743", "Peter Hulgaard - s194277"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/nullerh/02467_group4"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    

